package cinemabookingsystem2;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

public class CJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form CJFrame3
     */
    private CJFrame2 frm;
    private String duration;
    private String movieName;
    private String timeStart;
    private String roomName;
    
    private String showtimeID;
    
    private int[] seat = new int[120];
    
    private JToggleButton[] seatToggle = new JToggleButton[120];
    
        
    public CJFrame3(CJFrame2 frm, String duration, String movieName, String timeStart, String roomName, String showtimeID) {
        

        
        this.duration = duration;
        this.movieName = movieName;
        this.timeStart = timeStart;
        this.roomName = roomName;
        this.showtimeID = showtimeID;
        
        
        initComponents();
        this.seatToggleInitialization();
        this.allSeatsCheck();

        
        jPanel4.setLayout(new GridLayout(10, 12));
        this.setResizable(false);
        
        this.frm = frm;
        jlblRoomName.setText(roomName);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        stA1 = new javax.swing.JToggleButton();
        stA2 = new javax.swing.JToggleButton();
        stA3 = new javax.swing.JToggleButton();
        stA4 = new javax.swing.JToggleButton();
        stA5 = new javax.swing.JToggleButton();
        stA6 = new javax.swing.JToggleButton();
        stA7 = new javax.swing.JToggleButton();
        stA8 = new javax.swing.JToggleButton();
        stA9 = new javax.swing.JToggleButton();
        stA10 = new javax.swing.JToggleButton();
        stA11 = new javax.swing.JToggleButton();
        stA12 = new javax.swing.JToggleButton();
        stB1 = new javax.swing.JToggleButton();
        stB2 = new javax.swing.JToggleButton();
        stB3 = new javax.swing.JToggleButton();
        stB4 = new javax.swing.JToggleButton();
        stB5 = new javax.swing.JToggleButton();
        stB6 = new javax.swing.JToggleButton();
        stB7 = new javax.swing.JToggleButton();
        stB8 = new javax.swing.JToggleButton();
        stB9 = new javax.swing.JToggleButton();
        stB10 = new javax.swing.JToggleButton();
        stB11 = new javax.swing.JToggleButton();
        stB12 = new javax.swing.JToggleButton();
        stC1 = new javax.swing.JToggleButton();
        stC2 = new javax.swing.JToggleButton();
        stC3 = new javax.swing.JToggleButton();
        stC4 = new javax.swing.JToggleButton();
        stC5 = new javax.swing.JToggleButton();
        stC6 = new javax.swing.JToggleButton();
        stC7 = new javax.swing.JToggleButton();
        stC8 = new javax.swing.JToggleButton();
        stC9 = new javax.swing.JToggleButton();
        stC10 = new javax.swing.JToggleButton();
        stC11 = new javax.swing.JToggleButton();
        stC12 = new javax.swing.JToggleButton();
        stD1 = new javax.swing.JToggleButton();
        stD2 = new javax.swing.JToggleButton();
        stD3 = new javax.swing.JToggleButton();
        stD4 = new javax.swing.JToggleButton();
        stD5 = new javax.swing.JToggleButton();
        stD6 = new javax.swing.JToggleButton();
        stD7 = new javax.swing.JToggleButton();
        stD8 = new javax.swing.JToggleButton();
        stD9 = new javax.swing.JToggleButton();
        stD10 = new javax.swing.JToggleButton();
        stD11 = new javax.swing.JToggleButton();
        stD12 = new javax.swing.JToggleButton();
        stE1 = new javax.swing.JToggleButton();
        stE2 = new javax.swing.JToggleButton();
        stE3 = new javax.swing.JToggleButton();
        stE4 = new javax.swing.JToggleButton();
        stE5 = new javax.swing.JToggleButton();
        stE6 = new javax.swing.JToggleButton();
        stE7 = new javax.swing.JToggleButton();
        stE8 = new javax.swing.JToggleButton();
        stE9 = new javax.swing.JToggleButton();
        stE10 = new javax.swing.JToggleButton();
        stE11 = new javax.swing.JToggleButton();
        stE12 = new javax.swing.JToggleButton();
        stF1 = new javax.swing.JToggleButton();
        stF2 = new javax.swing.JToggleButton();
        stF3 = new javax.swing.JToggleButton();
        stF4 = new javax.swing.JToggleButton();
        stF5 = new javax.swing.JToggleButton();
        stF6 = new javax.swing.JToggleButton();
        stF7 = new javax.swing.JToggleButton();
        stF8 = new javax.swing.JToggleButton();
        stF9 = new javax.swing.JToggleButton();
        stF10 = new javax.swing.JToggleButton();
        stF11 = new javax.swing.JToggleButton();
        stF12 = new javax.swing.JToggleButton();
        stG1 = new javax.swing.JToggleButton();
        stG2 = new javax.swing.JToggleButton();
        stG3 = new javax.swing.JToggleButton();
        stG4 = new javax.swing.JToggleButton();
        stG5 = new javax.swing.JToggleButton();
        stG6 = new javax.swing.JToggleButton();
        stG7 = new javax.swing.JToggleButton();
        stG8 = new javax.swing.JToggleButton();
        stG9 = new javax.swing.JToggleButton();
        stG10 = new javax.swing.JToggleButton();
        stG11 = new javax.swing.JToggleButton();
        stG12 = new javax.swing.JToggleButton();
        stH1 = new javax.swing.JToggleButton();
        stH2 = new javax.swing.JToggleButton();
        stH3 = new javax.swing.JToggleButton();
        stH4 = new javax.swing.JToggleButton();
        stH5 = new javax.swing.JToggleButton();
        stH6 = new javax.swing.JToggleButton();
        stH7 = new javax.swing.JToggleButton();
        stH8 = new javax.swing.JToggleButton();
        stH9 = new javax.swing.JToggleButton();
        stH10 = new javax.swing.JToggleButton();
        stH11 = new javax.swing.JToggleButton();
        stH12 = new javax.swing.JToggleButton();
        stI1 = new javax.swing.JToggleButton();
        stI2 = new javax.swing.JToggleButton();
        stI3 = new javax.swing.JToggleButton();
        stI4 = new javax.swing.JToggleButton();
        stI5 = new javax.swing.JToggleButton();
        stI6 = new javax.swing.JToggleButton();
        stI7 = new javax.swing.JToggleButton();
        stI8 = new javax.swing.JToggleButton();
        stI9 = new javax.swing.JToggleButton();
        stI10 = new javax.swing.JToggleButton();
        stI11 = new javax.swing.JToggleButton();
        stI12 = new javax.swing.JToggleButton();
        stJ1 = new javax.swing.JToggleButton();
        stJ2 = new javax.swing.JToggleButton();
        stJ3 = new javax.swing.JToggleButton();
        stJ4 = new javax.swing.JToggleButton();
        stJ5 = new javax.swing.JToggleButton();
        stJ6 = new javax.swing.JToggleButton();
        stJ7 = new javax.swing.JToggleButton();
        stJ8 = new javax.swing.JToggleButton();
        stJ9 = new javax.swing.JToggleButton();
        stJ10 = new javax.swing.JToggleButton();
        stJ11 = new javax.swing.JToggleButton();
        stJ12 = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();
        jlblRoomName = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose your Seats");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(100, 100, 100));

        jLabel3.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SCREEN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(75, 0));

        jPanel6.setPreferredSize(new java.awt.Dimension(75, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.GridLayout(10, 12, 4, 3));

        stA1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA1.setText("A01");
        stA1.setPreferredSize(new java.awt.Dimension(54, 23));
        stA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stA1ActionPerformed(evt);
            }
        });
        jPanel4.add(stA1);

        stA2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA2.setText("A02");
        stA2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA2);

        stA3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA3.setText("A03");
        stA3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA3);

        stA4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA4.setText("A04");
        stA4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA4);

        stA5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA5.setText("A05");
        stA5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA5);

        stA6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA6.setText("A06");
        stA6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA6);

        stA7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA7.setText("A07");
        stA7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA7);

        stA8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA8.setText("A08");
        stA8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA8);

        stA9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA9.setText("A09");
        stA9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA9);

        stA10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA10.setText("A10");
        stA10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA10);

        stA11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA11.setText("A11");
        stA11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA11);

        stA12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stA12.setText("A12");
        stA12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stA12);

        stB1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB1.setText("B01");
        stB1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB1);

        stB2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB2.setText("B02");
        stB2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB2);

        stB3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB3.setText("B03");
        stB3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB3);

        stB4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB4.setText("B04");
        stB4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB4);

        stB5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB5.setText("B05");
        stB5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB5);

        stB6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB6.setText("B06");
        stB6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB6);

        stB7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB7.setText("B07");
        stB7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB7);

        stB8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB8.setText("B08");
        stB8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB8);

        stB9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB9.setText("B09");
        stB9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB9);

        stB10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB10.setText("B10");
        stB10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB10);

        stB11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB11.setText("B11");
        stB11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB11);

        stB12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stB12.setText("B12");
        stB12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stB12);

        stC1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC1.setText("C01");
        stC1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC1);

        stC2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC2.setText("C02");
        stC2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC2);

        stC3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC3.setText("C03");
        stC3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC3);

        stC4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC4.setText("C04");
        stC4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC4);

        stC5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC5.setText("C05");
        stC5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC5);

        stC6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC6.setText("C06");
        stC6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC6);

        stC7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC7.setText("C07");
        stC7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC7);

        stC8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC8.setText("C08");
        stC8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC8);

        stC9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC9.setText("C09");
        stC9.setPreferredSize(new java.awt.Dimension(54, 23));
        stC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stC9ActionPerformed(evt);
            }
        });
        jPanel4.add(stC9);

        stC10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC10.setText("C10");
        stC10.setPreferredSize(new java.awt.Dimension(54, 23));
        stC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stC10ActionPerformed(evt);
            }
        });
        jPanel4.add(stC10);

        stC11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC11.setText("C11");
        stC11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stC11);

        stC12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stC12.setText("C12");
        stC12.setPreferredSize(new java.awt.Dimension(54, 23));
        stC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stC12ActionPerformed(evt);
            }
        });
        jPanel4.add(stC12);

        stD1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD1.setText("D01");
        stD1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD1);

        stD2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD2.setText("D02");
        stD2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD2);

        stD3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD3.setText("D03");
        stD3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD3);

        stD4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD4.setText("D04");
        stD4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD4);

        stD5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD5.setText("D05");
        stD5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD5);

        stD6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD6.setText("D06");
        stD6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD6);

        stD7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD7.setText("D07");
        stD7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD7);

        stD8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD8.setText("D08");
        stD8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD8);

        stD9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD9.setText("D09");
        stD9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD9);

        stD10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD10.setText("D10");
        stD10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD10);

        stD11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD11.setText("D11");
        stD11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD11);

        stD12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stD12.setText("D12");
        stD12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stD12);

        stE1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE1.setText("E01");
        stE1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE1);

        stE2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE2.setText("E02");
        stE2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE2);

        stE3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE3.setText("E03");
        stE3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE3);

        stE4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE4.setText("E04");
        stE4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE4);

        stE5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE5.setText("E05");
        stE5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE5);

        stE6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE6.setText("E06");
        stE6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE6);

        stE7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE7.setText("E07");
        stE7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE7);

        stE8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE8.setText("E08");
        stE8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE8);

        stE9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE9.setText("E09");
        stE9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE9);

        stE10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE10.setText("E10");
        stE10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE10);

        stE11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE11.setText("E11");
        stE11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE11);

        stE12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stE12.setText("E12");
        stE12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stE12);

        stF1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF1.setText("F01");
        stF1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF1);

        stF2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF2.setText("F02");
        stF2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF2);

        stF3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF3.setText("F03");
        stF3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF3);

        stF4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF4.setText("F04");
        stF4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF4);

        stF5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF5.setText("F05");
        stF5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF5);

        stF6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF6.setText("F06");
        stF6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF6);

        stF7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF7.setText("F07");
        stF7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF7);

        stF8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF8.setText("F08");
        stF8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF8);

        stF9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF9.setText("F09");
        stF9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF9);

        stF10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF10.setText("F10");
        stF10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF10);

        stF11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF11.setText("F11");
        stF11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF11);

        stF12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stF12.setText("F12");
        stF12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stF12);

        stG1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG1.setText("G01");
        stG1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG1);

        stG2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG2.setText("G02");
        stG2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG2);

        stG3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG3.setText("G03");
        stG3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG3);

        stG4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG4.setText("G04");
        stG4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG4);

        stG5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG5.setText("G05");
        stG5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG5);

        stG6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG6.setText("G06");
        stG6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG6);

        stG7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG7.setText("G07");
        stG7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG7);

        stG8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG8.setText("G08");
        stG8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG8);

        stG9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG9.setText("G09");
        stG9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG9);

        stG10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG10.setText("G10");
        stG10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG10);

        stG11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG11.setText("G11");
        stG11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG11);

        stG12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stG12.setText("G12");
        stG12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stG12);

        stH1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH1.setText("H01");
        stH1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH1);

        stH2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH2.setText("H02");
        stH2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH2);

        stH3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH3.setText("H03");
        stH3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH3);

        stH4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH4.setText("H04");
        stH4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH4);

        stH5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH5.setText("H05");
        stH5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH5);

        stH6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH6.setText("H06");
        stH6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH6);

        stH7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH7.setText("H07");
        stH7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH7);

        stH8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH8.setText("H08");
        stH8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH8);

        stH9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH9.setText("H09");
        stH9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH9);

        stH10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH10.setText("H10");
        stH10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH10);

        stH11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH11.setText("H11");
        stH11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH11);

        stH12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stH12.setText("H12");
        stH12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stH12);

        stI1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI1.setText("I01");
        stI1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI1);

        stI2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI2.setText("I02");
        stI2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI2);

        stI3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI3.setText("I03");
        stI3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI3);

        stI4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI4.setText("I04");
        stI4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI4);

        stI5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI5.setText("I05");
        stI5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI5);

        stI6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI6.setText("I06");
        stI6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI6);

        stI7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI7.setText("I07");
        stI7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI7);

        stI8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI8.setText("I08");
        stI8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI8);

        stI9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI9.setText("I09");
        stI9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI9);

        stI10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI10.setText("I10");
        stI10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI10);

        stI11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI11.setText("I11");
        stI11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI11);

        stI12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stI12.setText("I12");
        stI12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stI12);

        stJ1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ1.setText("J01");
        stJ1.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ1);

        stJ2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ2.setText("J02");
        stJ2.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ2);

        stJ3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ3.setText("J03");
        stJ3.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ3);

        stJ4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ4.setText("J04");
        stJ4.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ4);

        stJ5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ5.setText("J05");
        stJ5.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ5);

        stJ6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ6.setText("J06");
        stJ6.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ6);

        stJ7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ7.setText("J07");
        stJ7.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ7);

        stJ8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ8.setText("J08");
        stJ8.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ8);

        stJ9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ9.setText("J09");
        stJ9.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ9);

        stJ10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ10.setText("J10");
        stJ10.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ10);

        stJ11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ11.setText("J11");
        stJ11.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ11);

        stJ12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        stJ12.setText("J12");
        stJ12.setPreferredSize(new java.awt.Dimension(54, 23));
        jPanel4.add(stJ12);

        btnBack.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jlblRoomName.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        jlblRoomName.setText("roomName");

        btnNext.setBackground(new java.awt.Color(255, 102, 102));
        btnNext.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(19, 19, 19)
                        .addComponent(jlblRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext)
                            .addComponent(jlblRoomName)
                            .addComponent(btnBack))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void stA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stA1ActionPerformed

    private void stC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stC10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stC10ActionPerformed

    private void stC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stC9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stC9ActionPerformed

    private void stC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stC12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stC12ActionPerformed

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        boolean checkSeatOrder = false;
        
        for (int i = 0; i < 120; i++) {
            if (seatToggle[i].isSelected())
                checkSeatOrder = true;
        }
        
        if (checkSeatOrder == false) {
            JOptionPane.showMessageDialog(null, "You have not selected any seat.", "Please select your seats", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for (int i = 0; i < 120; i++) {
            if (seatToggle[i].isSelected() == true) {
                seat[i] = 1;
            }        
        }
        
        CJFrame4 frm4 = new CJFrame4(this, movieName, timeStart, roomName, seat, showtimeID);
        frm4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNextActionPerformed
    
    public void resetseat(){
    for (int i=0; i<120; ++i){
        seat[i]=0;
    }
    }
 
    public void allSeatsCheck () {
        
        
        resetseat();
        
        String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=CinemaBookingSystem;user=sa;password=090803;encrypt=false";

        try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
            
            String SQL = "SELECT Ticket.roomseatID"
                        + " FROM Ticket"
                        + " JOIN Showtimes ON Ticket.showtimeID = Showtimes.showtimeID"
                        + " JOIN Movie ON Movie.movieID = Showtimes.movieID"
                        + " WHERE Movie.movieName = '" + movieName + "' AND Showtimes.timeStart = '" + timeStart + "'";
            ResultSet rs = stmt.executeQuery(SQL);

            // Iterate through the data in the result set and display it.
            // process query results
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            
            int movieCount = 0;
            
            while (rs.next()) {
                for (int i = 0; i < 120; i++) {
                       if (i == (Integer.parseInt(String.valueOf(rs.getObject(1)) ) - 1) % 120) {
                           seat[i] = 1;                       
                       }    
     
                }
            }
            

            
            for (int j = 0; j < 120; j++) {
                if (seat[j] == 1) {
                    seatToggle[j].setEnabled(false);
                }
            }
            
        } // Handle any errors that may have occurred.
        catch (SQLException e) {            
        }
    }
    
    public void setAllSeatsOff() {
        for (int i = 0; i < 120; i++) {
            seatToggle[i].setSelected(false);
        }
            
    }

    
    public void seatToggleInitialization () {
        seatToggle[0] = stA1;
        seatToggle[1] = stA2;
        seatToggle[2] = stA3;
        seatToggle[3] = stA4;
        seatToggle[4] = stA5;
        seatToggle[5] = stA6;
        seatToggle[6] = stA7;
        seatToggle[7] = stA8;
        seatToggle[8] = stA9;
        seatToggle[9] = stA10;
        seatToggle[10] = stA11;
        seatToggle[11] = stA12;
        seatToggle[12] = stB1;
        seatToggle[13] = stB2;
        seatToggle[14] = stB3;
        seatToggle[15] = stB4;
        seatToggle[16] = stB5;
        seatToggle[17] = stB6;
        seatToggle[18] = stB7;
        seatToggle[19] = stB8;
        seatToggle[20] = stB9;
        seatToggle[21] = stB10;
        seatToggle[22] = stB11;
        seatToggle[23] = stB12;
        seatToggle[24] = stC1;
        seatToggle[25] = stC2;
        seatToggle[26] = stC3;
        seatToggle[27] = stC4;
        seatToggle[28] = stC5;
        seatToggle[29] = stC6;
        seatToggle[30] = stC7;
        seatToggle[31] = stC8;
        seatToggle[32] = stC9;
        seatToggle[33] = stC10;
        seatToggle[34] = stC11;
        seatToggle[35] = stC12;
        seatToggle[36] = stD1;
        seatToggle[37] = stD2;
        seatToggle[38] = stD3;
        seatToggle[39] = stD4;
        seatToggle[40] = stD5;
        seatToggle[41] = stD6;
        seatToggle[42] = stD7;
        seatToggle[43] = stD8;
        seatToggle[44] = stD9;
        seatToggle[45] = stD10;
        seatToggle[46] = stD11;
        seatToggle[47] = stD12;
        seatToggle[48] = stE1;
        seatToggle[49] = stE2;
        seatToggle[50] = stE3;
        seatToggle[51] = stE4;
        seatToggle[52] = stE5;
        seatToggle[53] = stE6;
        seatToggle[54] = stE7;
        seatToggle[55] = stE8;
        seatToggle[56] = stE9;
        seatToggle[57] = stE10;
        seatToggle[58] = stE11;
        seatToggle[59] = stE12;
        seatToggle[60] = stF1;
        seatToggle[61] = stF2;
        seatToggle[62] = stF3;
        seatToggle[63] = stF4;
        seatToggle[64] = stF5;
        seatToggle[65] = stF6;
        seatToggle[66] = stF7;
        seatToggle[67] = stF8;
        seatToggle[68] = stF9;
        seatToggle[69] = stF10;
        seatToggle[70] = stF11;
        seatToggle[71] = stF12;
        seatToggle[72] = stG1;
        seatToggle[73] = stG2;
        seatToggle[74] = stG3;
        seatToggle[75] = stG4;
        seatToggle[76] = stG5;
        seatToggle[77] = stG6;
        seatToggle[78] = stG7;
        seatToggle[79] = stG8;
        seatToggle[80] = stG9;
        seatToggle[81] = stG10;
        seatToggle[82] = stG11;
        seatToggle[83] = stG12;
        seatToggle[84] = stH1;
        seatToggle[85] = stH2;
        seatToggle[86] = stH3;
        seatToggle[87] = stH4;
        seatToggle[88] = stH5;
        seatToggle[89] = stH6;
        seatToggle[90] = stH7;
        seatToggle[91] = stH8;
        seatToggle[92] = stH9;
        seatToggle[93] = stH10;
        seatToggle[94] = stH11;
        seatToggle[95] = stH12;
        seatToggle[96] = stI1;
        seatToggle[97] = stI2;
        seatToggle[98] = stI3;
        seatToggle[99] = stI4;
        seatToggle[100] = stI5;
        seatToggle[101] = stI6;
        seatToggle[102] = stI7;
        seatToggle[103] = stI8;
        seatToggle[104] = stI9;
        seatToggle[105] = stI10;
        seatToggle[106] = stI11;
        seatToggle[107] = stI12;
        seatToggle[108] = stJ1;
        seatToggle[109] = stJ2;
        seatToggle[110] = stJ3;
        seatToggle[111] = stJ4;
        seatToggle[112] = stJ5;
        seatToggle[113] = stJ6;
        seatToggle[114] = stJ7;
        seatToggle[115] = stJ8;
        seatToggle[116] = stJ9;
        seatToggle[117] = stJ10;
        seatToggle[118] = stJ11;
        seatToggle[119] = stJ12;
    }
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlblRoomName;
    private javax.swing.JToggleButton stA1;
    private javax.swing.JToggleButton stA10;
    private javax.swing.JToggleButton stA11;
    private javax.swing.JToggleButton stA12;
    private javax.swing.JToggleButton stA2;
    private javax.swing.JToggleButton stA3;
    private javax.swing.JToggleButton stA4;
    private javax.swing.JToggleButton stA5;
    private javax.swing.JToggleButton stA6;
    private javax.swing.JToggleButton stA7;
    private javax.swing.JToggleButton stA8;
    private javax.swing.JToggleButton stA9;
    private javax.swing.JToggleButton stB1;
    private javax.swing.JToggleButton stB10;
    private javax.swing.JToggleButton stB11;
    private javax.swing.JToggleButton stB12;
    private javax.swing.JToggleButton stB2;
    private javax.swing.JToggleButton stB3;
    private javax.swing.JToggleButton stB4;
    private javax.swing.JToggleButton stB5;
    private javax.swing.JToggleButton stB6;
    private javax.swing.JToggleButton stB7;
    private javax.swing.JToggleButton stB8;
    private javax.swing.JToggleButton stB9;
    private javax.swing.JToggleButton stC1;
    private javax.swing.JToggleButton stC10;
    private javax.swing.JToggleButton stC11;
    private javax.swing.JToggleButton stC12;
    private javax.swing.JToggleButton stC2;
    private javax.swing.JToggleButton stC3;
    private javax.swing.JToggleButton stC4;
    private javax.swing.JToggleButton stC5;
    private javax.swing.JToggleButton stC6;
    private javax.swing.JToggleButton stC7;
    private javax.swing.JToggleButton stC8;
    private javax.swing.JToggleButton stC9;
    private javax.swing.JToggleButton stD1;
    private javax.swing.JToggleButton stD10;
    private javax.swing.JToggleButton stD11;
    private javax.swing.JToggleButton stD12;
    private javax.swing.JToggleButton stD2;
    private javax.swing.JToggleButton stD3;
    private javax.swing.JToggleButton stD4;
    private javax.swing.JToggleButton stD5;
    private javax.swing.JToggleButton stD6;
    private javax.swing.JToggleButton stD7;
    private javax.swing.JToggleButton stD8;
    private javax.swing.JToggleButton stD9;
    private javax.swing.JToggleButton stE1;
    private javax.swing.JToggleButton stE10;
    private javax.swing.JToggleButton stE11;
    private javax.swing.JToggleButton stE12;
    private javax.swing.JToggleButton stE2;
    private javax.swing.JToggleButton stE3;
    private javax.swing.JToggleButton stE4;
    private javax.swing.JToggleButton stE5;
    private javax.swing.JToggleButton stE6;
    private javax.swing.JToggleButton stE7;
    private javax.swing.JToggleButton stE8;
    private javax.swing.JToggleButton stE9;
    private javax.swing.JToggleButton stF1;
    private javax.swing.JToggleButton stF10;
    private javax.swing.JToggleButton stF11;
    private javax.swing.JToggleButton stF12;
    private javax.swing.JToggleButton stF2;
    private javax.swing.JToggleButton stF3;
    private javax.swing.JToggleButton stF4;
    private javax.swing.JToggleButton stF5;
    private javax.swing.JToggleButton stF6;
    private javax.swing.JToggleButton stF7;
    private javax.swing.JToggleButton stF8;
    private javax.swing.JToggleButton stF9;
    private javax.swing.JToggleButton stG1;
    private javax.swing.JToggleButton stG10;
    private javax.swing.JToggleButton stG11;
    private javax.swing.JToggleButton stG12;
    private javax.swing.JToggleButton stG2;
    private javax.swing.JToggleButton stG3;
    private javax.swing.JToggleButton stG4;
    private javax.swing.JToggleButton stG5;
    private javax.swing.JToggleButton stG6;
    private javax.swing.JToggleButton stG7;
    private javax.swing.JToggleButton stG8;
    private javax.swing.JToggleButton stG9;
    private javax.swing.JToggleButton stH1;
    private javax.swing.JToggleButton stH10;
    private javax.swing.JToggleButton stH11;
    private javax.swing.JToggleButton stH12;
    private javax.swing.JToggleButton stH2;
    private javax.swing.JToggleButton stH3;
    private javax.swing.JToggleButton stH4;
    private javax.swing.JToggleButton stH5;
    private javax.swing.JToggleButton stH6;
    private javax.swing.JToggleButton stH7;
    private javax.swing.JToggleButton stH8;
    private javax.swing.JToggleButton stH9;
    private javax.swing.JToggleButton stI1;
    private javax.swing.JToggleButton stI10;
    private javax.swing.JToggleButton stI11;
    private javax.swing.JToggleButton stI12;
    private javax.swing.JToggleButton stI2;
    private javax.swing.JToggleButton stI3;
    private javax.swing.JToggleButton stI4;
    private javax.swing.JToggleButton stI5;
    private javax.swing.JToggleButton stI6;
    private javax.swing.JToggleButton stI7;
    private javax.swing.JToggleButton stI8;
    private javax.swing.JToggleButton stI9;
    private javax.swing.JToggleButton stJ1;
    private javax.swing.JToggleButton stJ10;
    private javax.swing.JToggleButton stJ11;
    private javax.swing.JToggleButton stJ12;
    private javax.swing.JToggleButton stJ2;
    private javax.swing.JToggleButton stJ3;
    private javax.swing.JToggleButton stJ4;
    private javax.swing.JToggleButton stJ5;
    private javax.swing.JToggleButton stJ6;
    private javax.swing.JToggleButton stJ7;
    private javax.swing.JToggleButton stJ8;
    private javax.swing.JToggleButton stJ9;
    // End of variables declaration//GEN-END:variables
}
